# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/yepeng/python_project/myqt/ui/first.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(850, 698)
        self.MyWindow = QtWidgets.QWidget(MainWindow)
        self.MyWindow.setObjectName("MyWindow")
        self.pushButton = QtWidgets.QPushButton(self.MyWindow)
        self.pushButton.setGeometry(QtCore.QRect(460, 220, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.MyWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 300, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.MyWindow)
        self.label.setGeometry(QtCore.QRect(60, 60, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.MyWindow)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.MyWindow)
        self.label_3.setGeometry(QtCore.QRect(330, 60, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.MyWindow)
        self.label_4.setGeometry(QtCore.QRect(450, 60, 60, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.MyWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 390, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.MyWindow)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 480, 101, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.MyWindow)
        self.graphicsView.setGeometry(QtCore.QRect(30, 210, 421, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_5 = QtWidgets.QPushButton(self.MyWindow)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 600, 113, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.spinBox = QtWidgets.QSpinBox(self.MyWindow)
        self.spinBox.setGeometry(QtCore.QRect(60, 120, 48, 24))
        self.spinBox.setObjectName("spinBox")
        self.lineEdit = QtWidgets.QLineEdit(self.MyWindow)
        self.lineEdit.setGeometry(QtCore.QRect(150, 130, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.MyWindow)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(self.label_4.lower)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "开始"))
        self.pushButton_2.setText(_translate("MainWindow", "B"))
        self.label.setText(_translate("MainWindow", "lable 1"))
        self.label_2.setText(_translate("MainWindow", "lable 2"))
        self.label_3.setText(_translate("MainWindow", "lable 3"))
        self.label_4.setText(_translate("MainWindow", "lable 4"))
        self.pushButton_3.setText(_translate("MainWindow", "C"))
        self.pushButton_4.setText(_translate("MainWindow", "D"))
        self.pushButton_5.setText(_translate("MainWindow", "OK"))
        self.lineEdit.setText(_translate("MainWindow", "这里输入"))
