'''
Date: 2021-02-24 05:19:47
LastEditTime: 2021-02-24 05:38:36
Author: Ye-P
Descripttion: 
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/yepeng/python_project/myqt/ui/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(850, 698)
        self.HttpClinet = QtWidgets.QWidget(MainWindow)
        self.HttpClinet.setObjectName("HttpClinet")
        self.pushButton = QtWidgets.QPushButton(self.HttpClinet)
        self.pushButton.setGeometry(QtCore.QRect(20, 130, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.HttpClinet)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 130, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.HttpClinet)
        self.label.setGeometry(QtCore.QRect(60, 60, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.HttpClinet)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.HttpClinet)
        self.label_3.setGeometry(QtCore.QRect(330, 60, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.HttpClinet)
        self.label_4.setGeometry(QtCore.QRect(450, 60, 60, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.HttpClinet)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 130, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.HttpClinet)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 130, 113, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.HttpClinet)
        self.graphicsView.setGeometry(QtCore.QRect(30, 210, 421, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_5 = QtWidgets.QPushButton(self.HttpClinet)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 600, 113, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.HttpClinet)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hello World"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "Hello"))
        self.pushButton_5.setText(_translate("MainWindow", "World"))
